/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.Ctr_FRM_VentanaNodos;
import javax.swing.JOptionPane;
import modelo.MetodosCliente;
/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaPrincipal extends javax.swing.JFrame {

    //Referencias
    Ctr_FRM_VentanaNodos ctr_FRM_VentanaNodos;
    
    public FRM_VentanaPrincipal() {
        initComponents();
        ctr_FRM_VentanaNodos = new Ctr_FRM_VentanaNodos(this);
        this.setSize(760, 680);
        this.setLocation(200, 5);
        agregarEventos();
    }
    
    public void agregarEventos() {
        this.jB_GenerarFicha.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_LlamarCliente.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_MayorMenor.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_MenorMayor.addActionListener(ctr_FRM_VentanaNodos);
    }

    
    public String[] getDatos() {
        
        String[] vector = new String[3];

        vector[0] = this.jT_NombreCliente.getText();
        vector[1] = this.jT_EdadCliente.getText();
        vector[2] = this.jT_NumeroComprobante.getText();
        
        return vector;
    
    }
    
    public void limpiarInterfaz() {
        
        this.jT_NombreCliente.setText("");
        this.jT_EdadCliente.setText("");
        this.jT_NumeroComprobante.setText("");
        
    }
    
    public void imprimirEnTextArea(String texto) {
        this.jT_ClienteEnEspera.setText(texto);
    }
    
    public void atendientoCliente(String texto) {
        this.jT_Atendiendo.setText(texto);
    }
    
    public void mensajeListaVacia() {
        JOptionPane.showMessageDialog(null, "La lista está vacía");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Cant_Nodos = new javax.swing.JLabel();
        jB_GenerarFicha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Atendiendo = new javax.swing.JTextArea();
        jL_NombreCliente = new javax.swing.JLabel();
        jT_NombreCliente = new javax.swing.JTextField();
        jT_EdadCliente = new javax.swing.JTextField();
        jL_EdadCliente = new javax.swing.JLabel();
        jL_NumeroComprobante = new javax.swing.JLabel();
        jLOrdenar = new javax.swing.JLabel();
        jB_MayorMenor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_ClienteEnEspera = new javax.swing.JTextArea();
        jB_LlamarCliente = new javax.swing.JButton();
        jT_NumeroComprobante = new javax.swing.JTextField();
        jB_MenorMayor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Cant_Nodos.setBackground(new java.awt.Color(0, 153, 0));
        jL_Cant_Nodos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jL_Cant_Nodos.setForeground(new java.awt.Color(0, 0, 0));
        jL_Cant_Nodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Cant_Nodos.setText("SISTEMA DE FICHAS MOPT ");
        jL_Cant_Nodos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_Cant_Nodos.setOpaque(true);
        getContentPane().add(jL_Cant_Nodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 670, 30));

        jB_GenerarFicha.setBackground(new java.awt.Color(0, 153, 0));
        jB_GenerarFicha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_GenerarFicha.setForeground(new java.awt.Color(0, 0, 0));
        jB_GenerarFicha.setText("CREAR NUEVA CITA");
        jB_GenerarFicha.setActionCommand("GenerarFicha");
        jB_GenerarFicha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_GenerarFicha.setFocusPainted(false);
        jB_GenerarFicha.setFocusable(false);
        jB_GenerarFicha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jB_GenerarFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 220, -1));

        jT_Atendiendo.setEditable(false);
        jT_Atendiendo.setBackground(new java.awt.Color(204, 204, 204));
        jT_Atendiendo.setColumns(20);
        jT_Atendiendo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jT_Atendiendo.setRows(5);
        jT_Atendiendo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jT_Atendiendo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 320, 200));

        jL_NombreCliente.setBackground(new java.awt.Color(0, 153, 0));
        jL_NombreCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_NombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        jL_NombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_NombreCliente.setText("NOMBRE");
        jL_NombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_NombreCliente.setOpaque(true);
        getContentPane().add(jL_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 24));

        jT_NombreCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jT_NombreCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT_NombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jT_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 220, 24));

        jT_EdadCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jT_EdadCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT_EdadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jT_EdadCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT_EdadClienteKeyTyped(evt);
            }
        });
        getContentPane().add(jT_EdadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 120, 24));

        jL_EdadCliente.setBackground(new java.awt.Color(0, 153, 0));
        jL_EdadCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_EdadCliente.setForeground(new java.awt.Color(0, 0, 0));
        jL_EdadCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_EdadCliente.setText("EDAD");
        jL_EdadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_EdadCliente.setOpaque(true);
        getContentPane().add(jL_EdadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, 24));

        jL_NumeroComprobante.setBackground(new java.awt.Color(0, 153, 0));
        jL_NumeroComprobante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_NumeroComprobante.setForeground(new java.awt.Color(0, 0, 0));
        jL_NumeroComprobante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_NumeroComprobante.setText("NÚMERO COMROBANTE");
        jL_NumeroComprobante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_NumeroComprobante.setOpaque(true);
        getContentPane().add(jL_NumeroComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 24));

        jLOrdenar.setBackground(new java.awt.Color(0, 153, 0));
        jLOrdenar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        jLOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLOrdenar.setText("ORDENAR LISTA");
        jLOrdenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLOrdenar.setOpaque(true);
        getContentPane().add(jLOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 180, 24));

        jB_MayorMenor.setBackground(new java.awt.Color(255, 255, 255));
        jB_MayorMenor.setForeground(new java.awt.Color(0, 0, 0));
        jB_MayorMenor.setText(">");
        jB_MayorMenor.setActionCommand("MayorMenor");
        jB_MayorMenor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_MayorMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 50, 24));

        jT_ClienteEnEspera.setEditable(false);
        jT_ClienteEnEspera.setBackground(new java.awt.Color(204, 204, 204));
        jT_ClienteEnEspera.setColumns(20);
        jT_ClienteEnEspera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jT_ClienteEnEspera.setRows(5);
        jT_ClienteEnEspera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jT_ClienteEnEspera);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 320, 200));

        jB_LlamarCliente.setBackground(new java.awt.Color(0, 153, 0));
        jB_LlamarCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_LlamarCliente.setForeground(new java.awt.Color(0, 0, 0));
        jB_LlamarCliente.setText("LLAMAR CLIENTE");
        jB_LlamarCliente.setActionCommand("LlamarCliente");
        jB_LlamarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_LlamarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 210, -1));

        jT_NumeroComprobante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jT_NumeroComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 120, 24));

        jB_MenorMayor.setBackground(new java.awt.Color(255, 255, 255));
        jB_MenorMayor.setText("<");
        jB_MenorMayor.setActionCommand("MenorMayor");
        jB_MenorMayor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_MenorMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 50, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-billetes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_EdadClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_EdadClienteKeyTyped
        // TODO add your handling code here:
        int k = (int)evt.getKeyChar();
//        if(k >= 0 || k) {
//            
//        }
    }//GEN-LAST:event_jT_EdadClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_GenerarFicha;
    private javax.swing.JButton jB_LlamarCliente;
    private javax.swing.JButton jB_MayorMenor;
    private javax.swing.JButton jB_MenorMayor;
    private javax.swing.JLabel jLOrdenar;
    private javax.swing.JLabel jL_Cant_Nodos;
    private javax.swing.JLabel jL_EdadCliente;
    private javax.swing.JLabel jL_NombreCliente;
    private javax.swing.JLabel jL_NumeroComprobante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jT_Atendiendo;
    private javax.swing.JTextArea jT_ClienteEnEspera;
    private javax.swing.JTextField jT_EdadCliente;
    private javax.swing.JTextField jT_NombreCliente;
    private javax.swing.JTextField jT_NumeroComprobante;
    // End of variables declaration//GEN-END:variables
}
