/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.Ctr_FRM_VentanaNodos;
import vista.FRM_Reportes;
import javax.swing.JOptionPane;
import modelo.MetodosCliente;
/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaPrincipal extends javax.swing.JFrame {

    //Referencias
    Ctr_FRM_VentanaNodos ctr_FRM_VentanaNodos;
    FRM_Reportes fRM_Reportes;
    
    public FRM_VentanaPrincipal() {
        initComponents();
        
        fRM_Reportes = new FRM_Reportes();
        ctr_FRM_VentanaNodos = new Ctr_FRM_VentanaNodos(this, fRM_Reportes);
        
        this.setSize(760, 680);
        this.setLocation(200, 5);
        agregarEventos();
        addItemComboBox();
    }
    
    public void agregarEventos() {
        
        this.jB_RegistrarCita.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_AtenderCliente.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_MayorMenor.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_MenorMayor.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_Eliminar.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_Modificar.addActionListener(ctr_FRM_VentanaNodos);
        this.jB_Reportes.addActionListener(ctr_FRM_VentanaNodos);
        
    }

    public void addItemComboBox() {
        this.jC_Prioridad.removeAllItems();
        this.jC_Prioridad.addItem("Normal");
        this.jC_Prioridad.addItem("Alta");
        this.jC_TipoServicio.removeAllItems();
        this.jC_TipoServicio.addItem("Caja");
        this.jC_TipoServicio.addItem("Plataforma");        
    }
    
    public String[] getDatos() {
        
        String[] vector = new String[5];

        vector[0] = this.jT_Cedula.getText();
        vector[1] = this.jT_NombreCliente.getText();
        vector[2] = this.jT_EdadCliente.getText();
        vector[3] = ""+this.jC_TipoServicio.getSelectedItem();
        vector[4] = ""+this.jC_Prioridad.getSelectedItem();
        
        return vector;
    
    }
    
    public String[] getDatosModificar() {
        
        String[] vector = new String[4];

        vector[0] = this.jT_NombreCliente.getText();
        vector[1] = this.jT_EdadCliente.getText();
        vector[2] = ""+this.jC_TipoServicio.getSelectedItem();
        vector[3] = ""+this.jC_Prioridad.getSelectedItem();
        
        return vector;
    
    }
    
    public void deshabilitarBotonReportes() {
        this.jB_Reportes.setEnabled(false);
    }
    
    public void habilitarBotonReportes() {
        this.jB_Reportes.setEnabled(true);
    }
    
    public String getCedula() {
        return this.jT_Cedula.getText();
    }
    
    public void limpiarInterfaz() {
        
        this.jT_Cedula.setText("");
        this.jT_NombreCliente.setText("");
        this.jT_EdadCliente.setText("");
        this.jC_TipoServicio.setSelectedItem(0);
        this.jC_Prioridad.setSelectedIndex(0);
        
    }
    
    public void limpiarTabla() {
        this.jT_ClienteEnEspera.setText("");
    }
    
    public void imprimirEnTextArea(String texto) {
        this.jT_ClienteEnEspera.setText(texto);
    }
    
    public void atendientoCliente(String texto) {
        this.jT_Atendiendo.setText(texto);
    }
    
    public void mensajeListaVacia() {
        JOptionPane.showMessageDialog(null, "La lista está vacía");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Cant_Nodos = new javax.swing.JLabel();
        jB_RegistrarCita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Atendiendo = new javax.swing.JTextArea();
        jL_NombreCliente = new javax.swing.JLabel();
        jT_NombreCliente = new javax.swing.JTextField();
        jT_EdadCliente = new javax.swing.JTextField();
        jL_EdadCliente = new javax.swing.JLabel();
        jL_TipoServicio = new javax.swing.JLabel();
        jL_Prioridad = new javax.swing.JLabel();
        jLOrdenar = new javax.swing.JLabel();
        jB_MayorMenor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_ClienteEnEspera = new javax.swing.JTextArea();
        jC_Prioridad = new javax.swing.JComboBox<>();
        jB_AtenderCliente = new javax.swing.JButton();
        jC_TipoServicio = new javax.swing.JComboBox<>();
        jL_Cedula = new javax.swing.JLabel();
        jT_Cedula = new javax.swing.JTextField();
        jB_MenorMayor = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();
        jB_Modificar = new javax.swing.JButton();
        jB_Reportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Cant_Nodos.setBackground(new java.awt.Color(0, 153, 0));
        jL_Cant_Nodos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jL_Cant_Nodos.setForeground(new java.awt.Color(0, 0, 0));
        jL_Cant_Nodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Cant_Nodos.setText("Departamento de Migración");
        jL_Cant_Nodos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_Cant_Nodos.setOpaque(true);
        getContentPane().add(jL_Cant_Nodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 670, 30));

        jB_RegistrarCita.setBackground(new java.awt.Color(0, 153, 0));
        jB_RegistrarCita.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_RegistrarCita.setForeground(new java.awt.Color(0, 0, 0));
        jB_RegistrarCita.setText("REGISTRAR CITA");
        jB_RegistrarCita.setActionCommand("GenerarFicha");
        jB_RegistrarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_RegistrarCita.setFocusPainted(false);
        jB_RegistrarCita.setFocusable(false);
        jB_RegistrarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jB_RegistrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 180, -1));

        jT_Atendiendo.setEditable(false);
        jT_Atendiendo.setBackground(new java.awt.Color(204, 204, 204));
        jT_Atendiendo.setColumns(20);
        jT_Atendiendo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jT_Atendiendo.setRows(5);
        jT_Atendiendo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jT_Atendiendo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 320, 200));

        jL_NombreCliente.setBackground(new java.awt.Color(0, 153, 0));
        jL_NombreCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_NombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        jL_NombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_NombreCliente.setText("NOMBRE");
        jL_NombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_NombreCliente.setOpaque(true);
        getContentPane().add(jL_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 24));

        jT_NombreCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jT_NombreCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT_NombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jT_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 220, 30));

        jT_EdadCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jT_EdadCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT_EdadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jT_EdadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 24));

        jL_EdadCliente.setBackground(new java.awt.Color(0, 153, 0));
        jL_EdadCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_EdadCliente.setForeground(new java.awt.Color(0, 0, 0));
        jL_EdadCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_EdadCliente.setText("EDAD");
        jL_EdadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_EdadCliente.setOpaque(true);
        getContentPane().add(jL_EdadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 24));

        jL_TipoServicio.setBackground(new java.awt.Color(0, 153, 0));
        jL_TipoServicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_TipoServicio.setForeground(new java.awt.Color(0, 0, 0));
        jL_TipoServicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_TipoServicio.setText("TIPO DE SERVICIO");
        jL_TipoServicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_TipoServicio.setOpaque(true);
        getContentPane().add(jL_TipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 180, 24));

        jL_Prioridad.setBackground(new java.awt.Color(0, 153, 0));
        jL_Prioridad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_Prioridad.setForeground(new java.awt.Color(0, 0, 0));
        jL_Prioridad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_Prioridad.setText("PRIORIDAD");
        jL_Prioridad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_Prioridad.setOpaque(true);
        getContentPane().add(jL_Prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 180, 24));

        jLOrdenar.setBackground(new java.awt.Color(0, 153, 0));
        jLOrdenar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        jLOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLOrdenar.setText("ORDENAR LISTA");
        jLOrdenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLOrdenar.setOpaque(true);
        getContentPane().add(jLOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 24));

        jB_MayorMenor.setBackground(new java.awt.Color(255, 255, 255));
        jB_MayorMenor.setForeground(new java.awt.Color(0, 0, 0));
        jB_MayorMenor.setText(">");
        jB_MayorMenor.setActionCommand("MayorMenor");
        jB_MayorMenor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_MayorMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 50, 24));

        jT_ClienteEnEspera.setEditable(false);
        jT_ClienteEnEspera.setBackground(new java.awt.Color(204, 204, 204));
        jT_ClienteEnEspera.setColumns(20);
        jT_ClienteEnEspera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jT_ClienteEnEspera.setRows(5);
        jT_ClienteEnEspera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jT_ClienteEnEspera);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 320, 200));

        jC_Prioridad.setBackground(new java.awt.Color(255, 255, 255));
        jC_Prioridad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jC_Prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jC_Prioridad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jC_Prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, -1));

        jB_AtenderCliente.setBackground(new java.awt.Color(0, 153, 0));
        jB_AtenderCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_AtenderCliente.setForeground(new java.awt.Color(0, 0, 0));
        jB_AtenderCliente.setText("ATENDER CLIENTE");
        jB_AtenderCliente.setActionCommand("LlamarCliente");
        jB_AtenderCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_AtenderCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 180, -1));

        jC_TipoServicio.setBackground(new java.awt.Color(255, 255, 255));
        jC_TipoServicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jC_TipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jC_TipoServicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jC_TipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 120, -1));

        jL_Cedula.setBackground(new java.awt.Color(0, 153, 0));
        jL_Cedula.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_Cedula.setForeground(new java.awt.Color(0, 0, 0));
        jL_Cedula.setText("CÉDULA");
        jL_Cedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_Cedula.setOpaque(true);
        getContentPane().add(jL_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, -1));

        jT_Cedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jT_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 220, 30));

        jB_MenorMayor.setBackground(new java.awt.Color(255, 255, 255));
        jB_MenorMayor.setText("<");
        jB_MenorMayor.setActionCommand("MenorMayor");
        jB_MenorMayor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_MenorMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 50, 24));

        jB_Eliminar.setBackground(new java.awt.Color(0, 153, 0));
        jB_Eliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        jB_Eliminar.setText("ELIMINAR");
        jB_Eliminar.setActionCommand("Eliminar");
        jB_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 110, 190, 30));

        jB_Modificar.setBackground(new java.awt.Color(0, 153, 0));
        jB_Modificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_Modificar.setForeground(new java.awt.Color(0, 0, 0));
        jB_Modificar.setText("MODIFICAR");
        jB_Modificar.setActionCommand("Modificar");
        jB_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 150, 190, 30));

        jB_Reportes.setBackground(new java.awt.Color(0, 153, 0));
        jB_Reportes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jB_Reportes.setForeground(new java.awt.Color(0, 0, 0));
        jB_Reportes.setText("REPORTES");
        jB_Reportes.setActionCommand("Reportes");
        jB_Reportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jB_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 310, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AtenderCliente;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_MayorMenor;
    private javax.swing.JButton jB_MenorMayor;
    private javax.swing.JButton jB_Modificar;
    private javax.swing.JButton jB_RegistrarCita;
    private javax.swing.JButton jB_Reportes;
    private javax.swing.JComboBox<String> jC_Prioridad;
    private javax.swing.JComboBox<String> jC_TipoServicio;
    private javax.swing.JLabel jLOrdenar;
    private javax.swing.JLabel jL_Cant_Nodos;
    private javax.swing.JLabel jL_Cedula;
    private javax.swing.JLabel jL_EdadCliente;
    private javax.swing.JLabel jL_NombreCliente;
    private javax.swing.JLabel jL_Prioridad;
    private javax.swing.JLabel jL_TipoServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jT_Atendiendo;
    private javax.swing.JTextField jT_Cedula;
    private javax.swing.JTextArea jT_ClienteEnEspera;
    private javax.swing.JTextField jT_EdadCliente;
    private javax.swing.JTextField jT_NombreCliente;
    // End of variables declaration//GEN-END:variables
}
