/*
 * @Autor Jorge Ignacio Elizondo Alvarado
 */
package vista;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_Reportes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Reportes
     */
    public FRM_Reportes() {
        initComponents();
        
        this.setSize(760, 680);
        this.setLocation(200, 5);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Reportes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_InformacionToda = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_PromedioEdad = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_CantidadPersonasCola = new javax.swing.JTextArea();
        jL_InformacionToda = new javax.swing.JLabel();
        jl_PromedioEdad = new javax.swing.JLabel();
        jl_CantidadPersonasCola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Reportes.setBackground(new java.awt.Color(0, 153, 0));
        jL_Reportes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_Reportes.setForeground(new java.awt.Color(0, 0, 0));
        jL_Reportes.setText("REPORTES");
        jL_Reportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_Reportes.setOpaque(true);

        jT_InformacionToda.setColumns(20);
        jT_InformacionToda.setRows(5);
        jScrollPane1.setViewportView(jT_InformacionToda);

        jT_PromedioEdad.setColumns(20);
        jT_PromedioEdad.setRows(5);
        jScrollPane2.setViewportView(jT_PromedioEdad);

        jT_CantidadPersonasCola.setColumns(20);
        jT_CantidadPersonasCola.setRows(5);
        jScrollPane3.setViewportView(jT_CantidadPersonasCola);

        jL_InformacionToda.setBackground(new java.awt.Color(0, 153, 0));
        jL_InformacionToda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jL_InformacionToda.setForeground(new java.awt.Color(0, 0, 0));
        jL_InformacionToda.setText("INFORMACIÓN");
        jL_InformacionToda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_InformacionToda.setOpaque(true);

        jl_PromedioEdad.setBackground(new java.awt.Color(0, 153, 0));
        jl_PromedioEdad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jl_PromedioEdad.setForeground(new java.awt.Color(0, 0, 0));
        jl_PromedioEdad.setText("PROMEDIO EDAD");
        jl_PromedioEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jl_PromedioEdad.setOpaque(true);

        jl_CantidadPersonasCola.setBackground(new java.awt.Color(0, 153, 0));
        jl_CantidadPersonasCola.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jl_CantidadPersonasCola.setForeground(new java.awt.Color(0, 0, 0));
        jl_CantidadPersonasCola.setText("CANTIDAD");
        jl_CantidadPersonasCola.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jl_CantidadPersonasCola.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jL_Reportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jL_InformacionToda)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jl_PromedioEdad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_CantidadPersonasCola)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Reportes)
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_InformacionToda)
                    .addComponent(jl_PromedioEdad)
                    .addComponent(jl_CantidadPersonasCola))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_InformacionToda;
    private javax.swing.JLabel jL_Reportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jT_CantidadPersonasCola;
    private javax.swing.JTextArea jT_InformacionToda;
    private javax.swing.JTextArea jT_PromedioEdad;
    private javax.swing.JLabel jl_CantidadPersonasCola;
    private javax.swing.JLabel jl_PromedioEdad;
    // End of variables declaration//GEN-END:variables
}
